#!/usr/bin/env node

import { execFileSync } from "node:child_process";

const [operation, database, ...args] = process.argv.slice(2);
const IDENTIFIER = /^[a-z][a-z0-9_]{0,62}$/;
const TYPES = new Map([
  ["text", "text"],
  ["varchar", "varchar(255)"],
  ["integer", "integer"],
  ["bigint", "bigint"],
  ["boolean", "boolean"],
  ["date", "date"],
  ["timestamptz", "timestamp with time zone"],
  ["jsonb", "jsonb"],
  ["uuid", "uuid"],
  ["bigserial", "bigint GENERATED BY DEFAULT AS IDENTITY"],
]);

function identifier(value) {
  if (!IDENTIFIER.test(value ?? "")) throw new Error("Invalid identifier");
  return `"${value}"`;
}

function literal(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function parsePayload(encoded) {
  const value = JSON.parse(Buffer.from(encoded ?? "", "base64url").toString("utf8"));
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Invalid payload");
  return value;
}

function run(sql) {
  return execFileSync("runuser", ["-u", "postgres", "--", "psql", "--dbname", database, "--no-align", "--tuples-only", "--set", "ON_ERROR_STOP=1"], {
    encoding: "utf8",
    input: sql,
    maxBuffer: 10 * 1024 * 1024,
    timeout: 10_000,
    stdio: ["pipe", "pipe", "pipe"],
  }).trim();
}

function jsonResult(sql, fallback) {
  const output = run(sql);
  process.stdout.write(output || JSON.stringify(fallback));
}

if (!IDENTIFIER.test(database ?? "")) throw new Error("Invalid database");

if (operation === "tables") {
  jsonResult(`
    SELECT json_build_object(
      'tables', COALESCE(json_agg(json_build_object(
        'name', c.relname,
        'estimatedRows', GREATEST(c.reltuples::bigint, 0),
        'size', pg_size_pretty(pg_total_relation_size(c.oid)),
        'columns', (SELECT json_agg(json_build_object(
          'name', a.attname,
          'type', format_type(a.atttypid, a.atttypmod),
          'nullable', NOT a.attnotnull,
          'primaryKey', EXISTS (
            SELECT 1 FROM pg_index i WHERE i.indrelid = c.oid AND i.indisprimary AND a.attnum = ANY(i.indkey)
          ),
          'editable', a.attgenerated = '' AND a.attidentity = ''
        ) ORDER BY a.attnum) FROM pg_attribute a WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped)
      ) ORDER BY c.relname) FILTER (WHERE c.oid IS NOT NULL), '[]'::json)
    )
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p');
  `, { tables: [] });
} else if (operation === "rows") {
  const table = identifier(args[0]);
  const offset = Number.parseInt(args[1] ?? "0", 10);
  const limit = Math.min(Math.max(Number.parseInt(args[2] ?? "50", 10), 1), 100);
  if (!Number.isInteger(offset) || offset < 0) throw new Error("Invalid offset");
  jsonResult(`
    SELECT json_build_object(
      'rows', COALESCE((SELECT json_agg(row_data) FROM (
        SELECT jsonb_build_object('__rowId', ctid::text) || to_jsonb(t) AS row_data
        FROM public.${table} t ORDER BY ctid LIMIT ${limit} OFFSET ${offset}
      ) page), '[]'::json),
      'total', (SELECT count(*) FROM public.${table})
    );
  `, { rows: [], total: 0 });
} else if (operation === "create-table") {
  const table = identifier(args[0]);
  const payload = parsePayload(args[1]);
  if (!Array.isArray(payload.columns) || payload.columns.length < 1 || payload.columns.length > 50) throw new Error("Invalid columns");
  let primaryKeys = 0;
  const columns = payload.columns.map((column) => {
    const name = identifier(column.name);
    const type = TYPES.get(column.type);
    if (!type) throw new Error("Invalid column type");
    if (column.primaryKey) primaryKeys += 1;
    return `${name} ${type}${column.primaryKey ? " PRIMARY KEY" : ""}${column.nullable || column.primaryKey ? "" : " NOT NULL"}`;
  });
  if (primaryKeys > 1) throw new Error("Only one primary key is supported");
  run(`CREATE TABLE public.${table} (${columns.join(", ")});`);
  process.stdout.write(JSON.stringify({ ok: true }));
} else if (operation === "add-column") {
  const table = identifier(args[0]);
  const payload = parsePayload(args[1]);
  const name = identifier(payload.name);
  const type = TYPES.get(payload.type);
  if (!type) throw new Error("Invalid column type");
  run(`ALTER TABLE public.${table} ADD COLUMN ${name} ${type}${payload.nullable ? "" : " NOT NULL"};`);
  process.stdout.write(JSON.stringify({ ok: true }));
} else if (operation === "drop-table") {
  run(`DROP TABLE public.${identifier(args[0])};`);
  process.stdout.write(JSON.stringify({ ok: true }));
} else if (operation === "insert-row") {
  const tableName = args[0];
  const table = identifier(tableName);
  const payload = parsePayload(args[1]);
  const entries = Object.entries(payload);
  if (entries.length < 1 || entries.length > 100) throw new Error("Invalid row");
  const columns = entries.map(([name]) => identifier(name));
  const values = entries.map(([name, value]) => `(${literal(name)}, ${value === null || value === "" ? "NULL" : literal(value)})`);
  run(`
    WITH input(key, value) AS (VALUES ${values.join(", ")}),
    payload AS (SELECT jsonb_object_agg(key, value) AS data FROM input)
    INSERT INTO public.${table} (${columns.join(", ")})
    SELECT ${columns.map((column) => `(jsonb_populate_record(NULL::public.${table}, payload.data)).${column}`).join(", ")} FROM payload;
  `);
  process.stdout.write(JSON.stringify({ ok: true }));
} else if (operation === "update-row") {
  const tableName = args[0];
  const table = identifier(tableName);
  const rowId = args[1];
  if (!/^\([0-9]+,[0-9]+\)$/.test(rowId ?? "")) throw new Error("Invalid row id");
  const payload = parsePayload(args[2]);
  const entries = Object.entries(payload);
  if (entries.length < 1 || entries.length > 100) throw new Error("Invalid row");
  const values = entries.map(([name, value]) => `(${literal(identifier(name).slice(1, -1))}, ${value === null || value === "" ? "NULL" : literal(value)})`);
  const assignments = entries.map(([name]) => {
    const column = identifier(name);
    return `${column} = (jsonb_populate_record(NULL::public.${table}, payload.data)).${column}`;
  });
  run(`WITH input(key, value) AS (VALUES ${values.join(", ")}), payload AS (SELECT jsonb_object_agg(key, value) AS data FROM input) UPDATE public.${table} SET ${assignments.join(", ")} FROM payload WHERE ctid = ${literal(rowId)}::tid;`);
  process.stdout.write(JSON.stringify({ ok: true }));
} else if (operation === "delete-row") {
  const rowId = args[1];
  if (!/^\([0-9]+,[0-9]+\)$/.test(rowId ?? "")) throw new Error("Invalid row id");
  run(`DELETE FROM public.${identifier(args[0])} WHERE ctid = ${literal(rowId)}::tid;`);
  process.stdout.write(JSON.stringify({ ok: true }));
} else {
  throw new Error("Unsupported database editor operation");
}